#include <iostream>
#include "d-hello.h"
#include "s-hello.h"
#include "version.h" // Header auto-generated by cmake

int main(int argc, char *argv[])
{
	if (argc > 0)
		std::cout << std::endl << "    Program " << argv[0] << " version: " << Example_VERSION_MAJOR << "." << Example_VERSION_MINOR << "." << Example_VERSION_PATCH << std::endl << std::endl;

	sHelloFun();
	dHelloFun();
	
	std::cout << std::endl;
	std::cout << "Type any char and press Enter" << std::endl;
	
	char c;
	std::cin >> c;
	
	return 0;
}